name: Vae
on:
  schedule:
  - cron: "0 16 * * *"
  
  workflow_dispatch:

jobs:
  main-job:
    name: Main Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run checkin
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date
          python3 ./Vae/main.py --cookie_string "${{ secrets.VAE_COOKIE }}"
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          SERVERCHAN_SENDKEY: ${{ secrets.SERVERCHAN_SENDKEY }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          BARK_DEVICEKEY: ${{ secrets.BARK_DEVICEKEY }}
          WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
  keepalive-job:
    name: Keepalive Workflow
    if: ${{ always() }}
    needs: main-job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: false
